import type { Linter } from 'eslint'
import reactA11y from 'eslint-plugin-jsx-a11y'

export default {
  name: 'dethdkn/react-a11y/rules',
  plugins: { 'react-a11y': reactA11y },
  rules: {
    'react-a11y/alt-text': ['warn'],
    'react-a11y/anchor-has-content': ['warn'],
    'react-a11y/anchor-is-valid': ['warn'],
    'react-a11y/aria-activedescendant-has-tabindex': ['warn'],
    'react-a11y/aria-props': ['warn'],
    'react-a11y/aria-proptypes': ['warn'],
    'react-a11y/aria-role': ['warn'],
    'react-a11y/aria-unsupported-elements': ['warn'],
    'react-a11y/autocomplete-valid': ['warn'],
    'react-a11y/click-events-have-key-events': ['warn'],
    'react-a11y/control-has-associated-label': ['warn'],
    'react-a11y/heading-has-content': ['warn'],
    'react-a11y/html-has-lang': ['warn'],
    'react-a11y/iframe-has-title': ['warn'],
    'react-a11y/img-redundant-alt': ['warn'],
    'react-a11y/interactive-supports-focus': ['warn'],
    'react-a11y/label-has-associated-control': ['warn'],
    'react-a11y/lang': ['warn'],
    'react-a11y/media-has-caption': ['warn'],
    'react-a11y/mouse-events-have-key-events': ['warn'],
    'react-a11y/no-access-key': ['warn'],
    'react-a11y/no-aria-hidden-on-focusable': ['warn'],
    'react-a11y/no-autofocus': ['warn'],
    'react-a11y/no-distracting-elements': ['warn'],
    'react-a11y/no-interactive-element-to-noninteractive-role': ['warn'],
    'react-a11y/no-noninteractive-element-interactions': ['warn'],
    'react-a11y/no-noninteractive-element-to-interactive-role': ['warn'],
    'react-a11y/no-noninteractive-tabindex': ['warn'],
    'react-a11y/no-redundant-roles': ['warn'],
    'react-a11y/no-static-element-interactions': ['warn'],
    'react-a11y/role-has-required-aria-props': ['warn'],
    'react-a11y/role-supports-aria-props': ['warn'],
    'react-a11y/scope': ['warn'],
    'react-a11y/tabindex-no-positive': ['warn'],
  },
} as Linter.Config
